// A response that the auth service will answer and tryConnection and on registrateUser
class LoginRegisterResponse {

  // If true, it means that the account exists or it has been created
  final bool isAllowedToEnterApp;

  final String message;

  // The UID stored within the local storage generated by Firebase Auth
  final String userUID;

  final String email;

  LoginRegisterResponse(this.isAllowedToEnterApp, this.message, this.userUID, this.email);
}