// A response that the auth service will answer and tryConnection and on registrateUser
class LoginRegisterResponse {

  // If true, it means that the account exists or it has been created
  final bool isAllowdToEnterApp;

  final String message;

  // The UID stored within the local storage generated by Firebase Auth
  final String userUID;

  LoginRegisterResponse(this.isAllowdToEnterApp, this.message, this.userUID);
}